server:
  port: 8761
spring:
  application:
    name: eureka-registry-server
  security:
    user:
      name: miracle
      password: 123456
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: true
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
