server:
  port: 9761


eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true

spring:
  application:
    name: miracle-gateway
  security:
    user:
      name: miracle
      password: 123456
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://localhost:10762
        predicates:
          - predicates:
              - path: /*