server:
  port: 10762

spring:
  application:
    name: miracle-comm
  security:
    user:
      name: miracle
      password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true